### PR TITLE
[ci/publishing] Fix generating nuget packages on build for dev releases

### LINKED ISSUE #351: Publishing dev version of nuget packages is failing
The last several commits to `main` have failed publishing the dev SDK.

The most recent failure:
https://github.com/pulumi/pulumi-dotnet/actions/runs/11002521163/job/30550806238#step:8:51

```
Project 'Pulumi' failed to publish the nuget package: couldn't the nuget package
Project 'Pulumi.Automation' failed to publish the nuget package: couldn't the nuget package
Project 'Pulumi.FSharp' failed to publish the nuget package: couldn't the nuget package
Unhandled exception. System.Exception: Some nuget packages were not published: [Pulumi; Pulumi.Automation; Pulumi.FSharp]
   at Program.publishSdks() in /home/runner/work/pulumi-dotnet/pulumi-dotnet/build/Program.fs:line 144
   at Program.main(String[] args) in /home/runner/work/pulumi-dotnet/pulumi-dotnet/build/Program.fs:line 227
```

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Resolves #351 

The error message in the issue suggests that `dotnet build` isn't creating the nuget package even though we have a property `GeneratePackageOnBuild` set in the project settings. 

~~This PR fixes the problem by explicitly executing `dotnet pack` against the projects before trying to find the nuget package and publishing it~~

EDIT: removed `TargetFramework` property from directory build props

### CODE REVIEW

File: build/Publish.fs [hunk 1]
```diff
@@ -35,19 +35,22 @@ type PublishResult =
...
-    if Shell.Exec("dotnet", buildNugetCmd, projectDir) <> 0 then
-        PublishResult.Failed(projectDir, "failed to build the nuget package")
+
+    if Shell.Exec("dotnet", cmd "build", projectDir) <> 0 then
+        PublishResult.Failed(projectDir, $"failed to build the project at {projectDir}")
     else
+        if Shell.Exec("dotnet", cmd "pack", projectDir) <> 0 then
+            PublishResult.Failed(projectDir, $"failed to pack the project at {projectDir}")
+        else
         let releaseDir = Path.Combine(projectDir, "bin", "Release")
```
Comment (justinvp) [inline build/Publish.fs:50]: Should this line and the lines below be indented?

**Review by justinvp — COMMENTED** [review]
Strange that `GeneratePackageOnBuild` stopped working...

This started failing with https://github.com/pulumi/pulumi-dotnet/commit/b6400f13cb84dfd6095f2386f66b4ae6f5cc6789

I think the underlying culprit is the [change](https://github.com/pulumi/pulumi-dotnet/commit/b6400f13cb84dfd6095f2386f66b4ae6f5cc6789#diff-53b0e0c38a16a02a12d7ac457774c2ea22d9211baa80eebf80e8917e07b600ba) to `sdk/Directory.Build.props` to add `<TargetFramework>net6.0</TargetFramework>`. If I remove that line, running `dotnet build --configuration Release` inside `sdk/Pulumi` produces the .nupkg.

Do we know why that line was necessary to add to `sdk/Directory.Build.props`? Wondering if we could remove it to go back to the old behavior without having to add the explicit `dotnet pack` command.

**Comment by Zaid-Ajaj** [comment]
> Do we know why that line was necessary to add to sdk/Directory.Build.props?

It doesn't seem necessary, the projects in `./sdk` already set the`TargetFrameworks` (not `TargetFramework`) so they don't require shared the property 🤔 I will remove it from `sdk/Directory.Build.props` and see if that breaks anything

File: build/Publish.fs (hunk 1 above)
Comment (Zaid-Ajaj) [reply build/Publish.fs:50]: `else` branch usually doesn't _have_ to be indented in F# (to reduce nesting)

**Review by julienp — APPROVED** [review]
