### PR TITLE
Fix program hanging when a resource transformation throws an exception

### LINKED ISSUE #174: Pulumi program hangs when resource transformation throws an exception
### What happened?

When using a `ResourceTransformation` as a stack option and that transform throws an exception, `pulumi preview` and `pulumi up` hang forever. 

### Expected Behavior

`pulumi preview` and `pulumi up` should not hang, instead, the transformation should catch errors and show them to users.

### Steps to reproduce

The following C# Pulumi program demonstrates the problem:
```cs
using System.Threading.Tasks;
using Pulumi;
using Pulumi.Aws.S3;

class MyStack : Stack
{
    static StackOptions Options() => new StackOptions()
    {
        ResourceTransformations = { FailingTransform() } 
    };

    public MyStack() : base(Options())
    {
        var bucket = new Bucket("my-bucket");
    }

    static ResourceTransformation FailingTransform() 
    {
        return args => 
        {
            throw new System.Exception("Boom!");
            return null;
        };
    }
}


class Program
{
    static Task<int> Main() => Deployment.RunAsync<MyStack>();
}
```

### Output of `pulumi about`

```
CLI          
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.0.2
dotnet  unknown

Host     
OS       darwin
Version  13.2.1
Arch     arm64

```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #291: Adding stack resource transformation to named value causes update to stop without returning error
### Describe what happened

When I add a resource transformation to a stack involving a `NamedValue` resource, it updates all the other resources in the stack, but just stops working. No error message, no panic and doesn't exit.

### Sample program

```csharp
using System;
using System.Collections.Generic;
using Pulumi;
using Pulumi.AzureNative.ApiManagement;
using Pulumi.AzureNative.ApiManagement.Inputs;
using Pulumi.AzureNative.Resources;

class MyStack : Stack
{
    public MyStack() : base(new StackOptions{ResourceTransformations = {MyTransformation}})
    {

        var resourceGroup = new ResourceGroup("apigmg-rg");

        var apimgm = new ApiManagementService("apimgm", new()
        {
            PublisherEmail = "piers@pulumi.com",
            PublisherName = "Piers",
            ResourceGroupName = resourceGroup.Name,
            Sku = new ApiManagementServiceSkuPropertiesArgs
            {
                Capacity = 0,
                Name = SkuType.Consumption
            },
            Tags = new InputMap<string>
            {
                {
                    "foo", "bar"
                }
            }
        });

        var nv = new NamedValue("nv", new()
        {
            DisplayName = "tenantNamedValueName",
            ResourceGroupName = resourceGroup.Name,
            ServiceName = apimgm.Name,
            Secret = false,
            Value = "tenantId"
        });
    }

    public static ResourceTransformationResult? MyTransformation(ResourceTransformationArgs args)
    {
        var tagProperty = args.Args.GetType().GetProperty("Tags");
        if (tagProperty != null) {
            var currentResourceTags = (InputMap<string>)tagProperty.GetValue(args.Args, null) ?? new InputMap<string>();
            currentResourceTags["env"] = "production";
            tagProperty.SetValue(args.Args, currentResourceTags, null);
            return new ResourceTransformationResult(args.Args, (CustomResourceOptions)args.Options);
        }
        return null;
    }

    
}
```

### Log output

Logs here: https://gist.github.com/pierskarsenbarg/774a2f184f0abc33e52cfeaa98baeeff

I actually waited until 11:33 to hit cancel so the time gap between 11:27 and 11:33 is the program just hanging

### Affected Resource(s)

_No response_

### Output of `pulumi about`

```
CLI
Version      3.121.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.48.0
language  dotnet        unknown

Host
OS       darwin
Version  14.5
Arch     arm64

This project is written in dotnet: executable='/usr/local/share/dotnet/dotnet' version='8.0.201'

Current Stack: pierskarsenbarg/azure-namedvalue/dev

TYPE                                             URN
pulumi:pulumi:Stack                              urn:pulumi:dev::azure-namedvalue::pulumi:pulumi:Stack::azure-namedvalue-dev
pulumi:providers:azure-native                    urn:pulumi:dev::azure-namedvalue::pulumi:providers:azure-native::default_2_48_0
azure-native:resources:ResourceGroup             urn:pulumi:dev::azure-namedvalue::azure-native:resources:ResourceGroup::apigmg-rg
azure-native:apimanagement:ApiManagementService  urn:pulumi:dev::azure-namedvalue::azure-native:apimanagement:ApiManagementService::apimgm


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/pierskarsenbarg
User           pierskarsenbarg
Organizations  pierskarsenbarg, karsenbarg, team-ce, gitlab-test-piers, demo
Token type     personal

Dependencies:
NAME                VERSION
Pulumi              3.64.0
Pulumi.AzureNative  2.48.0

Pulumi locates its logs in /var/folders/x8/cdd9j87s607fwpy0q62mfmmw0000gn/T/ by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Fixes #291 Fixes #174 (duplicate of the former)

The problem is that the task that is created for logging the exception never resolves. Simplified to use `Task.Run(...)` without `Task.ContinueWith(...)` and added an integration test to verify that a failing transformation actually exits the program without hanging.

### CODE REVIEW

File: integration_tests/integration_dotnet_test.go [hunk 1]
```diff
@@ -301,6 +301,19 @@ func TestLargeResourceDotNet(t *testing.T) {
 	})
 }
 
+// tests that when a resource transformation throws an exception, the program exists
```
Comment (julienp) [inline integration_tests/integration_dotnet_test.go:304]: I make this typo all the time :D

```suggestion
// tests that when a resource transformation throws an exception, the program exits
```

**Review by julienp — APPROVED** [review]
